# Generated by Django 2.2.6 on 2019-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enter',
            fields=[
                ('System_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.CharField(default='date', max_length=20)),
                ('Make', models.CharField(max_length=50)),
                ('Model_No', models.TextField(max_length=50)),
                ('Quantity', models.IntegerField(max_length=25)),
                ('Particulars', models.TextField(max_length=100)),
                ('Remarks', models.TextField(max_length=100)),
            ],
        ),
    ]
