# Generated by Django 2.2.6 on 2019-11-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enter',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
