# Generated by Django 2.2.6 on 2019-11-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('System_No', models.IntegerField()),
                ('Date', models.CharField(default='date', max_length=20)),
                ('Make', models.CharField(max_length=50)),
                ('Model_No', models.TextField(max_length=50)),
                ('Quantity', models.IntegerField()),
                ('Particulars', models.TextField(max_length=100)),
                ('Remarks', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Enter',
        ),
    ]
