# Generated by Django 2.2.6 on 2019-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msys', '0005_auto_20191125_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataentryacl',
            options={'verbose_name_plural': 'Advanced Computing Lab '},
        ),
        migrations.AlterModelOptions(
            name='dataentrycc1',
            options={'verbose_name_plural': 'Computer Lab 1'},
        ),
        migrations.AlterModelOptions(
            name='dataentrycc2',
            options={'verbose_name_plural': 'Computer Lab 2'},
        ),
        migrations.AlterField(
            model_name='dataentryacl',
            name='System_No',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataentrycc1',
            name='System_No',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dataentrycc2',
            name='System_No',
            field=models.CharField(max_length=20),
        ),
    ]
